# Continuous integration workflow for shimming-toolbox

name: CI

on: [push]
# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Download mock data
      run: |
        wget -O data.zip https://osf.io/7d2j5/?action=download
        unzip data.zip
        ls -la
